apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: maxpotasio/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: maxpotasio/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*.yaml
