apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: maxpotasio/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - infra/k8s/*.yaml
